import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
        h2{
          font-size:38px
        }
        h3{
          font-size:28px
        }
        `}
      </style>

      <Head>
        <title>NextJs Coder</title>
        <meta name="description" content="generated by next app" />
        <meta name="keywords" content="nextjs,huntingcoder blog,next js blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>NextJs Coder</h1>
        <div className={styles.imageDiv}>
        <Image className={styles.myImg} src="/home.avif" width={237} height={158} />
        </div>
        <p className={styles.description}>A blog for next js beginers..</p>

        <div className="">
          <h2>Latest Blogs</h2>
          <div>
            <h3>How to learn java script in 2022.</h3>
            <p>
              java script is most widly used language for serverside scrpiting
              languge which is very powerfull language..
            </p>
          </div>
          <div>
            <h3>How to learn java script in 2022.</h3>
            <p>
              java script is most widly used language for serverside scrpiting
              languge which is very powerfull language..
            </p>
          </div>
          <div>
            <h3>How to learn java script in 2022.</h3>
            <p>
              java script is most widly used language for serverside scrpiting
              languge which is very powerfull language..
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}
